apps: fix: ks_pkt_echo shared_q compilation error
Removed initialization of the shared_q parameter, which is no longer a
member of the tx_shadow_q struct.

Change-Id: Ia4df365fef8fef55d567badf47dd9c90744881c4
Reviewed-on: http://vgitil04.il.marvell.com:8080/47214
Tested-by: iSoC Platform CI <ykjenk@marvell.com>
Reviewed-by: Yuval Caduri <cyuval@marvell.com>